server:
  port: 8888
  http2:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Ulzo5eCpnTaC3EDb74jHuHQ4bZt5/jWoqmr9zDvRK41nwGM//z8r7Ut1DIqGOv4htr0Ph1hvJaTWbpYYGbpXeR5nsTfYIiWBAPjj+faZ+oirYmryKF55FpBfrPshV8fKL6M7IHYQW9haL80cBn1zCC1gQJKYuXn6+tjXaE9wtCsnPE/2UwHhZIuHtBb9L0nySTLf7WJTFs3feHDP6TIToKSO3B2doRfcEzKomYfUsh/QpUg/PtcbvMAAMHTQ5NSy)
    username: ENC(HoGt7dUuSI3OXlqWG5c/7Q==)
    password: ENC(AYg2AqtTFFjld89z21bghxogHpzsZfBl)

logging:
  level:
    root: info

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: update
        jdbc:
          time_zone: Asia/Seoul

jasypt:
  encryptor:
    bean: jasyptStringEncryptor